#spring.application.name=security_module

spring:
  application:
    name: security_module
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: ${db_url}
    password: ${db_password}
    username: ${db_username}

server:
  error:
    include-message: always